version: '3.9'

services:
  web:
    container_name: web-doctor-schedule
    build: ./docker/nginx
    image: nginx-docker-schedule
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docker/logs:/var/log/nginx
    working_dir: /var/www

  app:
    container_name: app-doctor-schedule
    image: phpfpm-doctor-schedule
    build: ./docker/php
    volumes:
      - ./:/var/www
    ports:
      - 9000:9000
    working_dir: /var/www
