version: '3.7'

services:
  web:
    container_name: web-doctor-schedule
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docker/logs:/var/log/nginx
    working_dir: /var/www

  app:
    container_name: app-doctor-schedule
    image: phpfpm-doctor-schedule
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
    ports:
      - 9000:9000
    working_dir: /var/www
